spring:
  datasource:
    url: jdbc:mysql://nj-cdb-re9tf3bd.sql.tencentcdb.com:63939/ads_ofl?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: ads_ofl
    password: huangqiu6451
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: NON_NULL
mybatis:
  typeAliasesPackage: com.ofl.promotion.manage.*
  mapperLocations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
server:
  port: 8088