spring:
  datasource:
    url: jdbc:mysql:///promotion?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  typeAliasesPackage: com.example.dao.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl